### ISSUE TITLE
About flying height

### ISSUE THREAD

**Issue by qmoji** [HKUST-Aerial-Robotics/Fast-Planner#10]
This is absolute great work!
But Is it possible to limit or fix the flying height? because it plans to fly over a wall.
![Screenshot from 2019-11-22 19-36-20](https://user-images.githubusercontent.com/15170611/69424858-9a9b9680-0d64-11ea-930b-c50b265b805d.png)

![Screenshot from 2019-11-22 19-37-40](https://user-images.githubusercontent.com/15170611/69424908-ba32bf00-0d64-11ea-8c6d-44be4991ef1c.png)

**Comment by GigaFlopsis** [comment]
Yeah! Will be better if you add the description of planner parameters from .launch file.

**Comment by ZbyLGsc** [comment]
@qmoji Theoretically this is caused by the limited sensing range of the sensor. The drone can not observed the regions overhead, and those regions are treated as collision free. In this case trajectories going over the walls, which is optimal depending on the currently available information, are generated.  

Currently you can resolve this problem by reducing the control input in z axis of the path searching (in kinodynamic_astar.cpp, um << ax, ay, az, reduce the possible values of az). This will make the drone takes less effort to change its height. Also, if you know the height of the ceiling, you can set the height in the .launch file directly (<param name="sdf_map/ceil_height" value="2.5" type="double"/>), so that region above it are treated as obstacles.

**Comment by qmoji** [comment]
@ZbyLGsc thank you very much!
I set `ceil_height `as 1,  and i got this...
![Screenshot from 2019-11-24 09-20-02](https://user-images.githubusercontent.com/15170611/69488351-58c53a00-0ea3-11ea-922b-95508f5aeaf3.png)
so i made some changes to the code:
```
for (double az = 0; az <= max_acc_ + 1e-3; az += max_acc_ * res)
{
  um << ax, ay, az;
  inputs.push_back(um);
}
```
it seems to work!
![Screenshot from 2019-11-24 09-33-11](https://user-images.githubusercontent.com/15170611/69488428-426bae00-0ea4-11ea-9ad9-5fd5b59843e4.png)

**Comment by devkishan920** [comment]
@qmoji How you managed to import you custom environment in simulation??
Is it .ply or .pcd. 

Thanks for help
