### ISSUE TITLE
Can this great project be used for 2D navigation of mobile robots?

### ISSUE THREAD

**Issue by shaoxiang** [HKUST-Aerial-Robotics/Fast-Planner#24]
Thank you very much for this great open source project. 
I want to use it in 2D navigation of mobile robot. Do you think it is suitable? Any suggestions？Thanks.

**Comment by ZbyLGsc** [comment]
@shaoxiang Yes of course, 2D is even easier than 3D. Just set z  to some fixed values.

**Comment by fxprime** [comment]
@ZbyLGsc Can i apply laser scan as sensor source (maybe convert to pointcloud first) for 2D navigation? Will it have some incompetible with algorithm? Thank you advanced.

**Comment by ZbyLGsc** [comment]
@fxprime Yes of course, we can also take sensor pose and pointcloud as input to update the map.
You may check the .launch file for details.

**Comment by LeeXujie** [comment]
> @shaoxiang Yes of course, 2D is even easier than 3D. Just set z to some fixed values.

Hello, Dr. Zhou. Which z should be set to a fixed value? And where to set it? Thank you very much!

**Comment by LiJing9876** [comment]
Hey,
First of all, great repo!

Similar question here, my problem is that the kino algorithm is planning a path that is not in the same direction as yaw direction, i.e in the case of a ground robot moving sidewise...
How can I overcome this issue?
Thanks ahead!

**Comment by zrd1234** [comment]
> @shaoxiang是的，当然，2D甚至比3D更容易。只需将 z 设置为一些固定值即可。
Hello, can you tell me how to modify it? I want to make a 2D plan. Thank you.

**Comment by LinSC666** [comment]
> @shaoxiang Yes of course, 2D is even easier than 3D. Just set z to some fixed values.
Hello,may I ask if you have successfully run the fast planner on the 2D differential-wheel robot?I found that changing the search state space to (v, w) resulted in a particularly strange trajectory for the front-end output dynamics constraint. Overall, it was not smooth and often had broken lines. Because I have just read Fast Planner's paper and code, and I still don't understand many of its essence, such as if after changing to a differential car, do UAV and differential robots use the Pontryagin principle to solve two-point boundary value problems in the same way?I transplanted this code intact because I don't know how to change the coefficients of many matrices，it's really just set z to some fixed calues? 
Looking forward to receiving feedback and guidance, thank you!

**Comment by LinSC666** [comment]
> 
Hello,may I ask if you have successfully run the fast planner on the 2D differential-wheel robot?I found that changing the search state space to (v, w) resulted in a particularly strange trajectory for the front-end output dynamics constraint. Overall, it was not smooth and often had broken lines. Because I have just read Fast Planner's paper and code, and I still don't understand many of its essence, such as if after changing to a differential car, do UAV and differential robots use the Pontryagin principle to solve two-point boundary value problems in the same way?I transplanted this code intact because I don't know how to change the coefficients of many matrices，it's really just set z to some fixed calues?
Looking forward to receiving feedback and guidance, thank you!

**Comment by LinSC666** [comment]
> @shaoxiang Yes of course, 2D is even easier than 3D. Just set z to some fixed values.

Hello,may I ask if you have successfully run the fast planner on the 2D differential-wheel robot?I found that changing the search state space to (v, w) resulted in a particularly strange trajectory for the front-end output dynamics constraint. Overall, it was not smooth and often had broken lines. Because I have just read Fast Planner's paper and code, and I still don't understand many of its essence, such as if after changing to a differential car, do UAV and differential robots use the Pontryagin principle to solve two-point boundary value problems in the same way?I transplanted this code intact because I don't know how to change the coefficients of many matrices，it's really just set z to some fixed calues?
Looking forward to receiving feedback and guidance, thank you!
