### ISSUE TITLE
Abnormal Behaviour using kino_replan

### ISSUE THREAD

**Issue by Stavya1993** [HKUST-Aerial-Robotics/Fast-Planner#72]
![FastPlannerFail](https://user-images.githubusercontent.com/56166385/98329821-1696f900-201f-11eb-95ae-1c8f14e1d71f.gif)

As you can see, even though there is no obstacle in front, the algorithm performs an obstacle avoiding maneuver. Just wanted to confirm how I can fix this behaviour.

Also wanted to extend my kudos to developers of this amazing algorithm!

**Comment by ZbyLGsc** [comment]
Have you change the max map size of the x,y,z axes? When your scene is too large the default map size may not be large enough to cover it. You may change the size in launch file.

**Comment by Stavya1993** [comment]
I have, Ive set the map size to 100 in x and y and 10 in z . The command itself is to move the quad to y = 18, x= -9, z =2.

**Comment by ZbyLGsc** [comment]
Then I would suggest again to check the mapping module. Although the in the simulator we see no obstacles, it seem the depth camera does see something and generate a 'wall' in front of it.

**Comment by Stavya1993** [comment]
Sure, Ill  check that again, post it when i find something! Will close the issue with the post to help others if they are stuck with similar problems / or in a few days if I cant find anything. Thanks!

**Comment by devkishan920** [comment]
> Sure, Ill check that again, post it when i find something! Will close the issue with the post to help others if they are stuck with similar problems / or in a few days if I cant find anything. Thanks!

@Stavya1993 , I am trying to test the fastplanner, by feeding it to the planner in rviz simulation, directly from depth cam d435i. Under kino_replan.launch, I have changed the cloud topic to /camera/depth/points 

But, now sure where it's visualising real object or some garbage simulation. Because the visualisation are not stable.

And, also have you implemented it on real drone.

Any help would be greatly appreciated
