### ISSUE TITLE
About max_vel and max_acc parameters

### ISSUE THREAD

**Issue by vislero** [HKUST-Aerial-Robotics/Fast-Planner#79]
Hi. 
First of all, thank you for nice work sharing.

We have tested your mapping and path planning algorithms on our LiDAR(Ouster)  and LOAM.

![Screenshot from 2020-11-20 00-36-27](https://user-images.githubusercontent.com/69630044/99688346-05db8e00-2ac9-11eb-8d1a-19124c511f32.png)

But when we decrease 1/10 times max_vel, max_acc, searching path (Red line in below figures) are diverging (below figure).

![Screenshot from 2020-11-20 00-33-07](https://user-images.githubusercontent.com/69630044/99688356-07a55180-2ac9-11eb-934d-e52ec1edebac.png)

And we found the similar problem in #64 .

So, we decrease 1/10 times search/resolution_astar in kino_algorithm.xml file like max_vel, max_acc.

But the result are not same as origin parameters. 

How to configure other parameters when we want to decrease max_vel and max_acc ?

Thank you.

**Comment by ZbyLGsc** [comment]
@vislero After some checks we find it is not only a parameter setting problem, but also a bug caused by B-spline parameterization. We just fix the problem and in our test the planner works under max_vel= max_acc = 0.5. Besides the params you mentioned, we also suggest to set search/max_tau to a larger value. This param represents the duration of each motion primitive in the path searching.

**Comment by vislero** [comment]
@ZbyLGsc 
Thank you very much !

**Comment by devkishan920** [comment]
> [@ZbyLGsc](https://github.com/ZbyLGsc) Thank you very much !

@nuyhead-hwang , i am trying to feed the d435i stream to fastplaner and test it. But can't pass it properly. Changed the cluoud topic to /camera/depth/points (in kino_replan.launch). But the object isn't stable, hence affecting path planning.

Any help would be greatly appreciated
